armhum6:
# Publish all joint states -----------------------------------
  joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 50

  joint2:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 1.0, i: 0.001, d: 0.10}
  joint3:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 1.0, i: 0.001, d: 0.10}